### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by kungpaogao** [cornell-dti/campus-density-android#19]
Add linting to our project: https://developer.android.com/studio/write/lint

**Comment by kungpaogao** [comment]
Can this be automated? Should we set certain lint warnings to raise errors? Otherwise, we would have to generate linting reports and occasionally fix manually.

**Comment by SamChou19815** [comment]
@kungpaogao You can configure the error levels in Gradle: https://developer.android.com/studio/write/lint#gradle
This is the API: https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.LintOptions.html#com.android.build.gradle.internal.dsl.LintOptions:check(java.lang.String)
Once you have decided the types of issues you want to escalate into error level, the CI can then include the lint step.
