### ISSUE TITLE
Consider app architecture

### ISSUE THREAD

**Issue by kungpaogao** [cornell-dti/campus-density-android#21]
We should try to refactor our code base so that it is more consistent with industry standards in terms of app architecture: https://developer.android.com/jetpack/docs/guide

### Overall Goals

The ultimate goal of this issue is to make our code easier to reason about, which will allow us to scale more effectively.

Implement:
- MVVM architecture
- reactive programming principles
- single source of truth for data

**Comment by SamChou19815** [comment]
I agree. Right now there are too many stuff happening in the `Activity` classes. Some of the data fetch and processing code should be refactored into separate classes or package level functions.

**Comment by kungpaogao** [comment]
Next steps should mainly revolve around cleaning up our API response structure:

- need to update `onSuccess` lambda to `onDone` (because that's what it is essentially)
- merge `onResponse` and `onBasic...Response`, the chained requests should act atomically (e.g., if the first succeeds and second fails, the whole request should fail)
   - we currently only check if the first request succeeds and mark the whole request success

**Comment by kungpaogao** [comment]
I think our API is in a good place for now, the next big goal is to create a repository class to maintain the state of our data. In terms of working towards this, these are a few tasks:

- decoupling Firebase authentication - Firebase should only be accessed by the API
- finalize model so that completed requests should fill the model and be put into the repository

**Comment by kungpaogao** [comment]
One thing we can do to keep `BaseActivity` and handle Firebase authentication is just have a loading animation/page (like in iOS) that is actually the `BaseActivity`

**Comment by kungpaogao** [comment]
While we've made some progress on this current code base, I think it will save a lot of time and effort to do [a rewrite](https://github.com/kungpaogao/flux-android/).

**Comment by kungpaogao** [comment]
See rewrite.
