### ISSUE TITLE
Hard coded a lot of things in switch that should be in config file

### ISSUE THREAD

**Issue by SamChou19815** [cornell-dti/campus-density-android#3]
The hard-coded switch is way too long.
https://github.com/cornell-dti/campus-density-android/blob/db3812ec096c184576ca42eb90cf280b0852889d/Density/app/src/main/java/org/cornelldti/density/density/FacilityPage.java#L260

**Comment by kungpaogao** [comment]
We've updated our code so the operating hours are pulled from the backend!
