### ISSUE TITLE
New COVID designs overflow on smaller screens

### ISSUE THREAD

**Issue by kungpaogao** [cornell-dti/campus-density-android#58]
@bungaepyo noticed a bug on his phone where the button text overflows (feel free to add screenshots)

**Device:** Samsung Galaxy S10e

**Comment by bungaepyo** [comment]
I totally forgot to create an issue thanks Andrew!
Here is a screenshot.
![Screenshot_20201018-203716_Flux](https://user-images.githubusercontent.com/49200001/96390301-00192280-1182-11eb-880a-63e097a76207.jpg)

**Comment by kungpaogao** [comment]
What device are you using again?

**Comment by bungaepyo** [comment]
Samsung Galaxy S10e
https://www.dimensions.com/element/samsung-galaxy-s10e-2019
