### ISSUE TITLE
Better handling for empty menus

### ISSUE THREAD

**Issue by kungpaogao** [cornell-dti/campus-density-android#59]
This is sort of an edge case, but our app shows too much blank space when there are open hours, but no menus.

**Official Menus**
![image](https://user-images.githubusercontent.com/11168401/96389359-1375bf00-117d-11eb-99f2-4d8e17ac934d.png)

**Our App**
![Screenshot_Flux_20201018-200458](https://user-images.githubusercontent.com/11168401/96389631-8f243b80-117e-11eb-99ef-76df79e4bae4.png)

**Comment by bungaepyo** [comment]
#67
