### ISSUE TITLE
[Bug report] Non-persistent dining hall filters

### ISSUE THREAD

**Issue by oliver-leung** [cornell-dti/campus-density-android#9]
Hey DTI,

I've been using the new Flux app recently, and it looks and feels great! However, I've been experiencing the following bug:

**Steps to reproduce**
1. Apply a campus location filter (North, West, Central).
1. Select a dining hall.
1. Go back.

**Expected behavior**
- The same filter is applied as in step 1, and the same dining halls appear.

**Actual behavior**
- The same filter appears to be applied as in step 1, but all dining halls appear, even ones that were previously filtered out.
- In order to apply the filter again, "All" needs to be selected, and then the filter needs to be applied.

**Device info**
- OnePlus 6
- Android 9, OnePlus 6 Beta 13

Thank you for your hard work on the app!

**Comment by kungpaogao** [comment]
Hey Oliver,

Thank you so much for the detailed feedback! We actually just fixed this bug yesterday, so we will try to push the latest version to the Play Store as soon as possible.

Once again, thanks for the report, and please let us know if you run into any other issues!

Best,
Andrew
